### ISSUE TITLE
Ignore issue

### ISSUE THREAD

**Issue by damianoneill** [elliotchance/ghost#10]
Is there a way to tag a line with a comment to ignore a complex line if you consider it valid, similar to what you can do with gometalinter?

// nolint: gosec

**Comment by elliotchance** [comment]
I had a thought yesterday that there was a good chance I would wake up to this very issue.

Yes, I will add this shortly.

**Comment by damianoneill** [comment]
Thanks Elliot

As an example the tool identified the following: 

```
./pkg/streamhttp/streamingserver_test.go:76: complexity is 8 (in TestServerOptions)
```

Which looks like 

```
	svr := NewServer(se, httptransport.NopRequestDecoder, EncodeStreamedResponse,
		ServerBefore(requestFunc("before_key", "BEFORE")),
		ServerAfter(responseFunc("AFTER")),
		ServerFinalizer(finalizerFunc(&final)))
```

I'm happy that this in my scenario is a false positive and would like to mark as ignore.

**Comment by damianoneill** [comment]
Thanks Elliot.
