### ISSUE TITLE
blogpost: social share links are broken

### ISSUE THREAD

**Issue by ghost** [elliotchance/ghost#11]
on http://elliot.land/post/ghost-locate-and-fix-overly-complex-lines-of-code-in-go you have twitter/fb/google buttons

they are embedding relative, not absolute URI's, so when I clicked the twitter one, Twitter's input box contains only: `Ghost: Locate And Fix Overly Complex Lines of Code In Go` rather than post link and/or your twitter handle

that button's current URI is `http://twitter.com/share?text=Ghost:%20Locate%20And%20Fix%20Overly%20Complex%20Lines%20of%20Code%20In%20Go&url=/permalink/359adf6386`

**Comment by elliotchance** [comment]
Oh bugger, that was part of the original template so it has probably been broken forever 😦

Thanks for letting me know! It is now fixed.
