### ISSUE TITLE
panic: (*ast.ChanType) (0x10de580,0xc000067860)

### ISSUE THREAD

**Issue by ipcjk** [elliotchance/ghost#2]
Gave it a try, but can't run:

`ghost  mlxsh.go  router_interface.go shellmode.go  shell_autocomplete.go 
panic: (*ast.ChanType) (0x10de580,0xc000067860)

goroutine 1 [running]:
main.exprComplexity(0x1115f20, 0xc000067860, 0x0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:247 +0x66d
main.exprsComplexity(0xc0000a1ae0, 0x2, 0x2, 0xc0000b1de0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:165 +0x6c
main.exprComplexity(0x1115ea0, 0xc00004de80, 0x0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:198 +0x627
main.exprsComplexity(0xc000043190, 0x1, 0x1, 0x0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:165 +0x6c
main.LineComplexity(0x1115ca0, 0xc00004dec0, 0x0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:83 +0x808
main.checkLine(0x1115ca0, 0xc00004dec0, 0x2201)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:68 +0x35
main.checkFunction(0xc0000b30e0)
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:63 +0x7e
main.main()
	/Users/joerg/golang/src/github.com/elliotchance/ghost/main.go:50 +0x2f8`

**Comment by elliotchance** [comment]
Thank you for raising this bug. It has been fixed in v1.2.1.
